package com.d121211005.rickandmortywiki.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF546500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0F052)
val md_theme_light_onPrimaryContainer = Color(0xFF171E00)
val md_theme_light_secondary = Color(0xFF00658C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC5E7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2D)
val md_theme_light_tertiary = Color(0xFF006877)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA3EEFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F25)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFE3E4D3)
val md_theme_light_onSurfaceVariant = Color(0xFF46483C)
val md_theme_light_outline = Color(0xFF77786A)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFB5D338)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF546500)
val md_theme_light_outlineVariant = Color(0xFFC7C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB5D338)
val md_theme_dark_onPrimary = Color(0xFF2A3400)
val md_theme_dark_primaryContainer = Color(0xFF3E4C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0F052)
val md_theme_dark_secondary = Color(0xFF80CFFF)
val md_theme_dark_onSecondary = Color(0xFF00344B)
val md_theme_dark_secondaryContainer = Color(0xFF004C6B)
val md_theme_dark_onSecondaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_tertiary = Color(0xFF52D7F0)
val md_theme_dark_onTertiary = Color(0xFF00363E)
val md_theme_dark_tertiaryContainer = Color(0xFF004E5A)
val md_theme_dark_onTertiaryContainer = Color(0xFFA3EEFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF46483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C8B8)
val md_theme_dark_outline = Color(0xFF919283)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF546500)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB5D338)
val md_theme_dark_outlineVariant = Color(0xFF46483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFBFDE42)
